"""SQLAlchemy 2 models owned by round 00 (R-STO-001, R-STO-006).

Tables: ``settings``, ``jobs``, ``cost_ledger``, ``alerts``, ``channel_state``.
Every table has ``created_at`` / ``updated_at`` (UTC, R-STO-001).  Later rounds
add their own tables with their own migrations.

Primary keys are generated by the application (ULID, or a natural string key
for key-value tables) because the primary key is part of the AES-GCM
associated data of every encrypted column (R-STO-002).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Float,
    Index,
    Integer,
    MetaData,
    String,
    Text,
)
from sqlalchemy import inspect as sa_inspect
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from twin.clock import now_utc
from twin.storage.crypto import SealedBlob
from twin.storage.ids import new_id
from twin.storage.types import (
    UTCDateTime,
    encrypted_column,
    sealed_json,
)

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

JOB_STATUSES = ("pending", "running", "done", "failed", "cancelled")
ALERT_SEVERITIES = ("info", "warning", "critical")
LEDGER_PROVIDERS = ("deepseek", "style_model", "other")
LEDGER_ACCOUNTS = ("daily", "one_time")


class Base(DeclarativeBase):
    """Declarative base: assigns primary keys first so encrypted fields can bind to them."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __init__(self, **kwargs: Any) -> None:
        mapper = sa_inspect(type(self))
        pk_names = [mapper.get_property_by_column(col).key for col in mapper.primary_key]
        for name in pk_names:
            if name in kwargs:
                setattr(self, name, kwargs.pop(name))
            elif name == "id":
                setattr(self, name, new_id())
        for name, value in kwargs.items():
            if not hasattr(type(self), name):
                raise TypeError(f"{type(self).__name__} has no attribute {name!r}")
            setattr(self, name, value)


class TimestampMixin:
    """``created_at`` / ``updated_at`` in UTC (R-STO-001)."""

    created_at: Mapped[datetime] = mapped_column(UTCDateTime(), default=now_utc, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        UTCDateTime(), default=now_utc, onupdate=now_utc, nullable=False
    )


class Setting(TimestampMixin, Base):
    """Runtime settings and internal state (R-CFG-003).

    ``value`` is sealed JSON.  ``history`` is a sealed JSON list of
    ``{"at", "by", "old", "new"}`` change records (newest last, capped).
    """

    __tablename__ = "settings"

    key: Mapped[str] = mapped_column(String(128), primary_key=True)
    value_ct: Mapped[SealedBlob] = encrypted_column("value", json=True)
    value = sealed_json()
    history_ct: Mapped[SealedBlob | None] = encrypted_column("history", json=True, nullable=True)
    history = sealed_json(optional=True)


class Job(TimestampMixin, Base):
    """Persistent task queue entry (R-ARCH-003)."""

    __tablename__ = "jobs"

    id: Mapped[str] = mapped_column(String(26), primary_key=True)
    type: Mapped[str] = mapped_column(String(128), nullable=False)
    payload_ct: Mapped[SealedBlob] = encrypted_column("payload", json=True)
    payload = sealed_json()
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=100)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="pending")
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    run_after: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False, default=now_utc)
    offpeak_only: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    deadline: Mapped[datetime | None] = mapped_column(UTCDateTime(), nullable=True)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    # one-time batch concept (R-LLM-014); estimation logic belongs to the business rounds
    batch_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    estimated_cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    requires_approval: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    approved_at: Mapped[datetime | None] = mapped_column(UTCDateTime(), nullable=True)
    approved_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    # execution bookkeeping
    started_at: Mapped[datetime | None] = mapped_column(UTCDateTime(), nullable=True)
    finished_at: Mapped[datetime | None] = mapped_column(UTCDateTime(), nullable=True)
    locked_by: Mapped[str | None] = mapped_column(String(64), nullable=True)

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'running', 'done', 'failed', 'cancelled')", name="status"
        ),
        CheckConstraint("attempts >= 0 AND max_attempts >= 1", name="attempts"),
        Index("ix_jobs_claim", "status", "priority", "run_after"),
        Index("ix_jobs_type", "type"),
        Index("ix_jobs_batch_id", "batch_id"),
    )


class CostLedger(TimestampMixin, Base):
    """One row per paid model call (R-LLM-006, R-LLM-014)."""

    __tablename__ = "cost_ledger"

    id: Mapped[str] = mapped_column(String(26), primary_key=True)
    at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False, default=now_utc)
    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    model: Mapped[str] = mapped_column(String(64), nullable=False)
    purpose: Mapped[str] = mapped_column(String(32), nullable=False)
    cache_hit_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cache_miss_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    completion_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_usd: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    peak: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    thinking: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    request_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # round 01 (migration 0002): which budget the call counts against (R-LLM-014)
    account: Mapped[str] = mapped_column(
        String(16), nullable=False, default="daily", server_default="daily"
    )
    batch_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    reasoning_tokens: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
    image_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")

    __table_args__ = (
        CheckConstraint("account IN ('daily', 'one_time')", name="account"),
        Index("ix_cost_ledger_at", "at"),
        Index("ix_cost_ledger_purpose", "purpose"),
        Index("ix_cost_ledger_account_at", "account", "at"),
        Index("ix_cost_ledger_batch_id", "batch_id"),
    )


class Alert(TimestampMixin, Base):
    """Operational alert (R-OPS-004).  ``detail`` never contains chat content."""

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(String(26), primary_key=True)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    severity: Mapped[str] = mapped_column(String(16), nullable=False, default="warning")
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    detail_ct: Mapped[SealedBlob | None] = encrypted_column("detail", json=True, nullable=True)
    detail = sealed_json(optional=True)
    dedup_key: Mapped[str | None] = mapped_column(String(128), nullable=True)
    notified_at: Mapped[datetime | None] = mapped_column(UTCDateTime(), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(UTCDateTime(), nullable=True)

    __table_args__ = (
        CheckConstraint("severity IN ('info', 'warning', 'critical')", name="severity"),
        Index("ix_alerts_category", "category", "created_at"),
        Index("ix_alerts_dedup_key", "dedup_key"),
    )


class ChannelState(TimestampMixin, Base):
    """Key/value state of the chat channel (cursor, bound user, ...; round 02)."""

    __tablename__ = "channel_state"

    key: Mapped[str] = mapped_column(String(128), primary_key=True)
    value_ct: Mapped[SealedBlob] = encrypted_column("value", json=True)
    value = sealed_json()
